### PR TITLE
Streams

### PR DESCRIPTION
**Pull request by AlexFinkel**
Refactoring to have ifstrOpen and ofstrOpen create and return streams, instead of calling 'open' on an existing stream.

As well as saving a few lines of code, this provides a central point at which changes to how streams are opened can be made.

### CODE REVIEW

**Comment by AlexFinkel** [comment]
Hi Alex, any thoughts on this one?

We might be better off deleting this pull request in favour of documenting and then implementing a more complete strategy for I/O in rna-star.

**Comment by alexdobin** [comment]
Hi Alex,

I was planning to pull it in, and then add the error indentifiers as we discussed.
Hopefully, today or tomorrow. What do you have in mind for a more complete I/O strategy?

Cheers
Alex

**Comment by AlexFinkel** [comment]
Nothing new, just consistency - as you mentioned, the usage of the fstrOpen functions isn't ubiquitous, and the difficulty with choosing error identifiers makes it hard to add everywhere.

I don't think it's a high priority, but in terms of long-term maintainability it should be useful to have a clear single way of doing things, especially as interest in star grows and a lot of patches start coming in.

**Comment by alexdobin** [comment]
I agree that it would be great to have it consistent throughout the code. Actually, a lot of things require this kind of criticial re-coding, I just never have enough time for that.

How about this - for now, I will pull in these few changes you made, and will introduce the file name/line/function in the error messages, and we will see how it goes. And then we can work on making all of the input/output consistent.

**Pull request merged**
