### PR TITLE
Added STAR-Fusion for mapping junction and fusion reads to reference annotations and generating a final report

### PR DESCRIPTION
**Pull request by brianjohnhaas**
Hi Alex,

I included the code under the 'extras/star-fusion' area. There's a README.txt describing how it all works, and an example provided in a 'test/' area.

Please let me know if it gives you any trouble.

Many thanks! :)

~brian

### CODE REVIEW

**Comment by jasper1918** [comment]
Great work including this functionality to provide more comprehensive reporting. All tests passed. However I did encounter some errors running some samples:

"Intervals must have positive width at STAR_spanning_to_genes.pl line 49:"

I can dig in a little more Monday if needs be.

**Comment by brianjohnhaas** [comment]
Thanks, Jeff!   There's an easy fix for this. I've encountered it before
myself in some other applications.  I'll update the code tomorrow and send
another pull request.

best,

~brian


On Sat, Mar 28, 2015 at 11:02 PM, Jeff S Jasper <notifications@github.com>
wrote:

> Great work including this functionality to provide more comprehensive
> reporting. All tests passed. However I did encounter some errors running
> some samples:
>
> "Intervals must have positive width at STAR_spanning_to_genes.pl line 49:"
>
> I can dig in a little more Monday if needs be.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87343921>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
I've updated the code to only map alignment segments that are > 1 base in length.  This should resolve the issue that Jeff was encountering on some data sets.  Please give it a whirl and let me know if any problems are encountered.

many thanks!

~brian

**Comment by jasper1918** [comment]
Thanks Brian!

I have tested on a couple hundred samples and the fix has solved the >1bp length error.

One thing I did notice is that known internal gene fusions or partial tandem duplications are not reported using this workflow even in the case of strong support in the junction file. For what its worth, both the junction and spanning reads files contain the data but these are not brought forth into the final file. 

Cheers

-Jeff

**Comment by ndaniel** [comment]
Hi Jeff,

please could you elaborate on what do you mean by "internal gene fusions"? Do you mean [cis-splicing](http://en.wikipedia.org/wiki/Trans-splicing) (a.k.a. normal splicing)? 

Daniel

**Comment by jasper1918** [comment]
Sorry--I see how that was confusing. I was referring to internal
duplication events.

-Jeff

On Monday, March 30, 2015, Daniel Nicorici <notifications@github.com> wrote:

> Hi Jeff,
>
> please could you elaborate on what do you mean by "internal gene fusions"?
> Do you mean cis-splicing <http://en.wikipedia.org/wiki/Trans-splicing>
> (a.k.a. normal splicing)?
>
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87639841>.
>


-- 
Jeff Jasper
(801) 372-2395

**Comment by brianjohnhaas** [comment]
Hi guys,

I was trying to keep it simple and focus on only those fusions that involve
two different genes and involve junction reads that target exon-exon
boundaries through known splice junctions.  This is because (afaik) most
known fusions related to cancer have involved these types of fusions, and
the specificity of such predictions would be higher than including all
possible fusion types (where the false positive rate will presumably
skyrocket).

We can certainly look to classify the other types of discordant or aberrant
read alignments, but that extends beyond what I was trying to focus on.
For internal deletions, I don't think I'd rely on RNA-Seq data but instead
require DNA-Seq data, given that RNA-Seq could simply be identifying rare
splicing events or artifacts that might not be trusted.

This is a good conversation to have. At the very least, we can update the
documentation to make it very clear to users what the limitations of the
current process are, and to encourage those interested in other types of
reads, events, etc., to dig deeper into the raw STAR outputs - or encourage
other processes to be built out to further classify the other types of
reads.

I have another tool that I'm building out that works on top of STAR-Fusion
and some other prediction methods to help improve specificity and enable
further interrogation of these events... hopefully ready to share soon.

best,

~brian


On Mon, Mar 30, 2015 at 7:36 AM, Jeff S Jasper <notifications@github.com>
wrote:

> Sorry--I see how that was confusing. I was referring to internal
> duplication events.
>
> -Jeff
>
> On Monday, March 30, 2015, Daniel Nicorici <notifications@github.com>
> wrote:
>
> > Hi Jeff,
> >
> > please could you elaborate on what do you mean by "internal gene
> fusions"?
> > Do you mean cis-splicing <http://en.wikipedia.org/wiki/Trans-splicing>
> > (a.k.a. normal splicing)?
> >
> > Daniel
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/alexdobin/STAR/pull/30#issuecomment-87639841>.
> >
>
>
> --
> Jeff Jasper
> (801) 372-2395
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87641106>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by ndaniel** [comment]
Ok. I understand that "internal duplication events" means duplication events which take place within the *same* gene. Right?

**Comment by ndaniel** [comment]
Hi Brian,

there are plenty of fusion genes in cancers where the fusion are not *re-using* known exon-exon boundaries! ;-) Here is a nice RNA-dataset for testing fusions (it has 9 very well know fusions which do not use known exon-exon boundaries):

[SRR1548811 dataset from NCBI SRA database](http://www.ncbi.nlm.nih.gov/sra/?term=SRR1548811)

from article W.B. Tembe et al., Open-access synthetic spike-in mRNA-seq data for cancer gene fusions, BMC Genomics 2014.

Cheers,
Daniel

**Comment by jasper1918** [comment]
Great points. I only bring this up because I am comparing output of
control samples to characterize sensitivity and specificity and noticed the
dropout. These types of internal duplications are common in leukemia with
the MLL gene.




On Monday, March 30, 2015, Daniel Nicorici <notifications@github.com> wrote:

> Hi Brian,
>
> there are plenty of fusion genes in cancers where the fusion are not
> *re-using* known exon-exon boundaries! ;-) Here is a nice RNA-dataset for
> testing fusions (it has 9 very well know fusions which do not use known
> exon-exon boundaries):
>
> SRR1548811 dataset from NCBI SRA database
> <http://www.ncbi.nlm.nih.gov/sra/?term=SRR1548811>
>
> from article W.B. Tembe et al., Open-access synthetic spike-in mRNA-seq
> data for cancer gene fusions, BMC Genomics 2014.
>
> Cheers,
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87648499>.
>


-- 
Jeff Jasper
(801) 372-2395

**Comment by brianjohnhaas** [comment]
Ah... thanks!  I'll give it a look.   The simplest thing to do in order to
accommodate this is to just take the junction reads and, for those that
don't map to annotated splice junctions, map the segments to exons as done
in the case of the spanning reads.    I'll put some thought into this.
Maybe we'll need another column in the output file that indicates the
number of non-canonical/non-reference junction reads supporting a given
fusion between two genes.

I think the internal-gene duplication issue is quite interesting, but
perhaps would benefit from a separate and more specialized process for
mining those features. It could still be part of STAR-Fusion, but maybe
it's something that Jeff would want to integrate given the relevant data
sets and controls, etc.

best,

~brian


On Mon, Mar 30, 2015 at 7:54 AM, Daniel Nicorici <notifications@github.com>
wrote:

> Hi Brian,
>
> there are plenty of fusion genes in cancers where the fusion are not
> *re-using* known exon-exon boundaries! ;-) Here is a nice RNA-dataset for
> testing fusions (it has 9 very well know fusions which do not use known
> exon-exon boundaries):
>
> SRR1548811 dataset from NCBI SRA database
> <http://www.ncbi.nlm.nih.gov/sra/?term=SRR1548811>
>
> from article W.B. Tembe et al., Open-access synthetic spike-in mRNA-seq
> data for cancer gene fusions, BMC Genomics 2014.
>
> Cheers,
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87648499>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Another thought... Right now, I'm using the junction/spliced reads to
define the orientation of the fusion gene pair.   If the junction reads
still map to splice sites, even if non-reference, I can still use that
information to properly orient the gene pair in the fusion (left gene,
right gene), but if they aren't and the RNA-Seq data aren't
strand-specific, then it might be somewhat ambiguous as to which is the
left vs. the right gene in the fusion pair.

Am I just being dense here? ;)

~b

**Comment by ndaniel** [comment]
Hi Brian,

it is possible to specify if gene is 5'end or 3'end partner for a genes fusion even if the sample preparation protocol is not strand specific (by looking to the gene/exon strand info from the GTF file) in RNA-seq data! Also, there are genes fusions which are known to be reciprocal which means that both A-B and B-A  (where one has gene A and gene B) can be found simultaneously in the same RNA-seq dataset.

Cheers,
Daniel

**Comment by brianjohnhaas** [comment]
Got it.  OK - perhaps I was being a little dense. ;)   The way the
STAR-Fusion wrapper is currently organized, it definitely requires junction
reads and spanning reads, where the junction read is orienting the fusion.

I'll put some more thought into these more complicated scenarios.  For now,
though, the system should function pretty well / comparable to what was
done in the pan-cancer studies that relied on STAR.    I'll take a look at
some of these other studies and find a better path forward.  False positive
rates in fusion-finding efforts tend to be quite high.  The 'actionable'
cancer fusions that I'm aware of and that have been well-studied have been
guiding much of my current strategy.



On Mon, Mar 30, 2015 at 8:51 AM, Daniel Nicorici <notifications@github.com>
wrote:

> Hi Brian,
>
> it is possible to specify if gene is 5'end or 3'end partner for a genes
> fusion even if the sample preparation protocol is not strand specific (by
> looking to the gene/exon strand info from the GTF file) in RNA-seq data!
> Also, there are genes fusions which are known to be reciprocal which means
> that both A-B and B-A (where one has gene A and gene B) can be found
> simultaneously in the same RNA-seq dataset.
>
> Cheers,
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87665552>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by ndaniel** [comment]
Hi Brian!

Actually there are fusion finders which have really low false positive rates at finding fusion genes! For example see [FusionCatcher](https://github.com/ndaniel/fusioncatcher) which is actually using STAR aligner (beside another three aligners that are BWA, BOWTIE, BOWTIE2,  and BLAT) for finding fusion genes with very low false positive rates!

Here is a very nice [dataset](http://www.ncbi.nlm.nih.gov/sra/?term=SRR1548811) with very known known fusion genes, from article W.B. Tembe et al., Open-access synthetic spike-in mRNA-seq data for cancer gene fusions, BMC Genomics, 2014.

Cheers,
Daniel

P.S. I am the developer of FusionCatcher.

**Comment by brianjohnhaas** [comment]
Fantastic.

I've been playing with FusionCatcher too.  I'm a fan. :)   I'll write you
separately sometime soon to discuss some FusionCatcher issues.

My main focus is Trinity software development and looking at ways in which
Trinity can add value to fusion-finding.  I'm picturing it in the context
of some ensembl approach, that leverages STAR and potentially some other
methods.

btw - FusionCatcher has one of the very best software installers I've come
across!  Very nice work!!!  (in addition to being good at fusion prediction)

~b

On Mon, Mar 30, 2015 at 9:20 AM, Daniel Nicorici <notifications@github.com>
wrote:

> Hi Brian!
>
> Actually there are fusion finders which have really low false positive
> rates at finding fusion genes! For example see FusionCatcher
> <https://github.com/ndaniel/fusioncatcher> which is actually using STAR
> aligner (beside another three aligners that are BWA, BOWTIE, BOWTIE2, and
> BLAT) for finding fusion genes with very low false positive rates!
>
> Here is a very nice dataset
> <http://www.ncbi.nlm.nih.gov/sra/?term=SRR1548811> with very known known
> fusion genes, from article W.B. Tembe et al., Open-access synthetic
> spike-in mRNA-seq data for cancer gene fusions, BMC Genomics, 2014.
>
> Cheers,
> Daniel
>
> P.S. I am the developer of FusionCatcher.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87675291>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Hi Daniel - would you be willing to write me directly?  I've been playing
with FusionCatcher and have a couple for you, particularly wrt to the Tembe
et al. data set you pointed me to earlier.

I'm bhaas@broadinstitute.org

many thanks,

~brian

On Mon, Mar 30, 2015 at 7:31 AM, Daniel Nicorici <notifications@github.com>
wrote:

> Hi Jeff,
>
> please could you elaborate on what do you mean by "internal gene fusions"?
> Do you mean cis-splicing <http://en.wikipedia.org/wiki/Trans-splicing>
> (a.k.a. normal splicing)?
>
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/pull/30#issuecomment-87639841>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Hi all,

Based on discussions with Daniel, I've rewritten the code so that it's capable of finding fusions that are both consistent with reference exon splicing junctions as well as those that are not (intra-exon fusions).  The README is updated to reflect these changes as well as to explain the other relevant parameters.

I still aim to do some more rigorous testing/evaluation before suggesting we fully integrate it into the official STAR repo, but the system is definitely ready for others to start playing with.  Feedback appreciated!

thanks, all!

~brian

**Comment by brianjohnhaas** [comment]
actually - hold off on any rigorous testing just yet.  It worked well on some simple data sets, but the FP rate is way too high right now...  I'll work to resolve this shortly and will post once it's ready.

**Comment by brianjohnhaas** [comment]
OK - now it's ready. :)    It doesn't do any filtering of false positives based on sequence similarity between fusion pairs... instead it only maps the aberrant read alignments to the reference annotations.

I've now set the default annotation to be used as gencode.v19, and it's included in the package.  The user only needs to run STAR-Fusion like so:

     STAR-Fusion -S Chimeric.out.sam -J Chimeric.out.junction

In addition to the star-fusion.fusion_candidates.txt file, it generates a few useful intermediates so users will have access to the specific reads identified as junction or spanning reads.

Ultimately, my FusionInspector tool (still under development) will focus on adding a bunch of downstream filters along with visualization.

Alex - once you're ready, we could aim to make including this as 'beta' status and we'll continue to harden it over time.    We could also entertain releasing this as a separate project on github, with separate release schedules, and I could make you a co-owner of it.  Just let me know what you think is best.  I'm thinking the latter might actually be the best strategy, given how quickly you and I turn things around.

Many thanks,

~brian

**Comment by brianjohnhaas** [comment]
Hi all,

I've added STAR-Fusion here:
https://github.com/STAR-Fusion/STAR-Fusion

which will make it easier to maintain separately from the STAR codebase.  Alex - I've invited you as a developer in case you want to join.  Perhaps you could include a link to it in the STAR documentation.

Thanks, everyone!

~brian

**Pull request closed without merging**
