### PR TITLE
Makefile for manual;Travis-CI automated build

### PR DESCRIPTION
**Pull request by nathanhaigh**
Ability to build STAR and the PDF manual using:
```bash
make STAR manual
# or
make all
```

The `.travis.yml` can be used by Travis-CI to automatically install a minimal TeX Live environment, using the profile and install script included, and run the above `make STAR manual` command. Build success/failures of the source and documentation will be caught earlier.

In addition, any pull requests will trigger a Travis-CI build on the merged-pull request. That way, contributions from others can be more easily tested to ensure they don't break the build process.

### CODE REVIEW

**Comment by alexdobin** [comment]
Thanks for the nice updates, Nathan!

**Comment by nathanhaigh** [comment]
No worries!

I have a few more in mind but they might result in changing the way you manage your project. I might open an issue to discuss them.  Although I'll be heading on parental leave imminently so I might wait a few weeks.

**Comment by alexdobin** [comment]
Hi Nathan,

It's a great idea to discuss any complex changes to the code and project organization before starting working on them. It's very hard for me to merge complex pull requests, since many people depend on robust operation of the code.

Good luck on your paternal leave!
Cheers
Alex

**Comment by nathanhaigh** [comment]
Indeed. BTW: If you register on travis-ci.org and enable your STAR repo, you'll start to benefit from all the Travis-CI goodness. Also, you'll then be able to provide a visual cue as to the project's current build status by adding the following markdown code to the top-level `README.md`:
```
[![Build Status](https://travis-ci.org/alexdobin/STAR.svg)](https://travis-ci.org/alexdobin/STAR)
```

**Pull request merged**
