### PR TITLE
build improvements

### PR DESCRIPTION
**Pull request by wookietreiber**
The `LDFLAGS` assignment in `Makefile` was completely overriding the user-specified `LDFLAGS`. I am using a non-standard location for my zlib installation and I have set the following in my environment:

    export LDFLAGS="-L/usr/local/zlib/1.2.8-1/lib"

This does not get picked up by the old `Makefile` because `LDFLAGS` is overridden with the `:=` assignment.

This change renames `LDFLAGS` in `Makefile` to `LDFLAGS_shared` and adds `LDFLAGS` (the now user-specified one) to all linking stages.

### CODE REVIEW

**Comment by wookietreiber** [comment]
Also related to the previous `LDFLAGS` commit regarding zlib in non-standard location is usage of the widely known `CPPFLAGS` variable, which points to the headers, e.g.:

    export CPPFLAGS="-I/usr/local/zlib/1.2.8-4/include"

**Comment by wookietreiber** [comment]
This PR is invalidated by the recent changes to `Makefile`.

**Comment by alexdobin** [comment]
Hi Christian,

I had incorporated your changes in the Makefile in a slightly different form, thanks a lot for suggesting them. Hopefully, this is satisfactory for your needs.

Cheers
Alex

**Comment by wookietreiber** [comment]
Thanks for incorporating some of the changes. Unfortunately, these don't cover everything that is needed to pick up all of the user-specified options. I will draft a new PR with the missing changes.

**Comment by wookietreiber** [comment]
Please see PR #80.

**Pull request closed without merging**
