### PR TITLE
header needed for python scipy mmread compatibility

### PR DESCRIPTION
**Pull request by k3yavi**

### CODE REVIEW

**Comment by alexdobin** [comment]
Thanks a lot, Avi!

**Comment by k3yavi** [comment]
My pleasure, just one more thing which I was not able to figure out how to fix.
The file which contains the gene names order (as per the matrix) seems to off by a new line or something? If I use the binary in the master branch, it seems to be giving lower-half of the file as blank and the upper half as jumbled up gene names.

**Comment by alexdobin** [comment]
Hi Avi,

there was issue #556 reporting the same probem, and I think I fixed it in the latest patch on master - please try it out. I will make a tagged release tomorrow.

Cheers
Alex

**Comment by zhangguy** [comment]
Hi @alexdobin 
The cellranger matrix.mtx file is space delimited while the STARsolo matrix.mtx is tab delimited. This makes Suerat unable to load. Could you also modify this?
Thanks.

**Comment by alexdobin** [comment]
Hi @zhangguy 

I have changed from tabs to spaces, please try the latest patch on Github master.
I will tag 2.7.0c tomorrow.

Cheers
Alex

**Comment by zhangguy** [comment]
Hi @alexdobin 
Thanks for the quick fix for the tab delimit issue. The binary in the main brach is working.

However there is another issue as pointed out by @k3yavi , the first line of genes.tsv is empty. If I read into Seurat using the Read10X function it'll make the first gene name as NA. Do you think the gene names are also shifted by one? Thanks.

**Comment by zhangguy** [comment]
Hi @alexdobin 
Worked. Lightning fast.
Cheers,
zhangguy

**Pull request merged**
