### PR TITLE
Feature/posix shared memory

### PR DESCRIPTION
**Pull request by gvessere**
Hi @alexdobin 
This pull request is with regards to a change we have had to make in order for STAR to function in the Illumina BaseSpace environment. The changes were to create an additional class to manage shared memory (SharedMemory.cpp). The shared memory API (SysV API) you use does not play nice with Linux containers which is the technology we use in BaseSpace. More specifically, it isn't possible to tell a container to start with a specified amount of shared memory, the default shmmax in a container becomes the kernel default value which is far too low for STAR. I switched out the touchpoints to the SysV API into the equivalent calls in the POSIX API and that plays nicer with Linux containers where the amount of shared memory available is specified using a tmpfs mount point capacity. I left the possibility to keep compiling the code with the original SysV API, which occurs when you call make without arguments. Compiling STAR with the new changes should be done using 'make POSIXSHARED'.
The refactoring led to some reshuffling of code in the Genome.cpp file and that simplified the logic in there significantly. We have conducted testing (with the help of Felix Schlesinger and Steve Lee) to verify STAR functions just the same as before. Also, I introduced the use of semaphore shared counters, that seems to fix some issues we found with the LoadAndRemove feature.

Looking to get your feedback and possible integration of these changes in your repo.

thanks!

### CODE REVIEW

**Comment by alexdobin** [comment]
Hi Gery,

this is an excellent contribution, thanks a lot! 
The genome loading code indeed grew very cluttered with time.
After reviewing your code, I will merge it into the master. 
Please let me know if you are working (or planning to) on other parts of the code, as I am planning to introduce extensive changes to the main mapping algorithm in the next couple of months.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Gery,

there seems to be a problem with --genomeLoad LoadAndRemove option.
When I start STAR without genome loaded, it prints 
"incremented shared memory fragment usage to 3"
and at the end it says 
"2 other job(s) are attached to the shared memory segment, will not remove it."
while there are no other STAR jobs running. So it seems that the counting is not initialized properly.
STAR was compiled with default make.

Cheers
Alex

**Comment by felixschlesinger** [comment]
This seems to be related to resetting the semaphore count. If I start a LoadAndRemove run and cancel it while the genome is still in memory and then start another one the old STAR would detect that the genome in memory is unused at the end of the second run and remove it. The new STAR instead starts the second run with a count of 1 already, hence goes 1 -> 2 -> 1 and never removes the genome. Deleting the shared memory with ipcrm does not change this, but running STAR remove does.

**Comment by felixschlesinger** [comment]
With this patch, the above is true for both Sys V and Posix shared memory.I am not sure if this is a problem. If STAR LoadAndRemove is aborted, the user needs to run STAR REMOVE to cleanup.
I am not sure how complicated it would be to ensure (as much as possible) that STAR LoadAndRemove always executes the 'Remove' part.

**Comment by gvessere** [comment]
Just saw these comments. Indeed this is an issue: when a run is interrupted with ctrl-c, then everything gets left dirty. I tried to write something that capture sigabrt and other common failure signals, but I stopped as it wasn't playing nice with having it in a class object, also it's sort of an inelegant solution. In the current state 'star remove' will clean things up, but it's not obvious to users that they must do that. We just need a way to detect the bad state or let the user know how to detect the bad state, any ideas? counting other start processes?

**Comment by alexdobin** [comment]
Hi Felix, Gery,

I confirmed the behavior Felix described.
In my LoadAndRemove option, I have used, at the end of STAR run, SysV call:
        struct shmid_ds shmStat;
        shmctl(shmID,IPC_STAT,&shmStat);
Then shmStat.shm_nattch=the number of processes attached to the shm, and I can decide whether to remove it or not.
Is there a similar call for POSIX shm?
I think it's best not to rely on the history of STAR calls and terminations to determine how many processes are attached to an shm.
If such an option is not available for POSIX, I would rather remove it completely from POSIX implementation, and instruct users to use Remove at the end of their runs.
But I'd like to keep the default LoadAndRemove behavior for the SysV implementation.

Cheers
Alex

**Comment by felixschlesinger** [comment]
In our workflow, always explicitly running 'STAR remove' is certainly reasonable. In a way users have to plan for that anyway, since the last STAR LoadAndRemove run may be aborted and leave the genome in memory. With Sys V the shared genome can also be deleted with the 'ipcrm' command. I am not aware of an equivalent for POSIX though. 

I do not remember all the details anyway, but we sometimes had problems with the old implementation of LoadAndRemove as well, where it would not remove the genome (I think related to many processes operating on it at the same time on a highly loaded machine), so I like the explicit semaphore approach in principle. 
One possible solution might be for the new semaphore based system to always reduce the counter to 0 at startup, if the genome is not actually loaded in memory (or even if it is loaded but no process is attached in Sys V). Then if a user cancels STAR and later deletes the genome with 'ipcrm' (as they already have to do now) the next run of LoadAndRemove should work. I have not studied the code in enough detail to know if that works though. Thoughts?

Felix

**Comment by felixschlesinger** [comment]
But just speaking for our current use case, all we really need is to have the posix interface work with 'LoadAndKeep' (loading the genome exactly once no matter how many processes are started) and the one call to 'Remove' to unload it. So Alex, if you prefer to minimize the total changes, disabling LoadAndRemove in POSIX and reverting the SysV interface to your previous system of counting should work as well. But that will of course make it harder later to completely replace the SysV interface with POSIX, which otherwise in principle should be possible.

**Comment by alexdobin** [comment]
This post (from 2012) http://rhaas.blogspot.com/2012/06/absurd-shared-memory-limits.html
indicates that only SysV shm can determine the number of attached processes. The solution they have for the POSIX implementation is to have an extra SysV shm segment (below the kernel shm limit) to be used just to count the number of attached processes. Sounds a bit complicated to me.

Initializing the counter to 0 if the genome is not loaded will, of course, help - however, if any of the jobs crash, the shm will not be removed - while in the SysV implementation it only happens if the last job crashes.

I think we could have the LoadAndRemove option to have slightly different behaviors for SysV (using my previous implementation) and POSIX in Gery's implementation.

**Comment by felixschlesinger** [comment]
That would certainly work for us (if you do not mind keeping both interfaces around, at least for a while).

**Comment by alexdobin** [comment]
Sure, I have no problem with two interfaces. Gery, are you on board with this solution?
Do you want to re-implement the SysV solution, or would you want me to do it?
I would also like to re-direct the shm messages to the Log.out rather than cerr, at least for the SysV implementation.

**Comment by gvessere** [comment]
One other way is to try implementing the signal catching next to the main function (not in the SharedMem class static init like I was trying). It seems pretty straight forward to make it work that way, we won't be able to catch a SIGKILL (sent through kill -9 only). All others like SIGSEGV, SIGTERM etc.. can be caught and used to keep the counter healthy in normal user operations including ctrl-c. 

Either solution would work, let me know and I'll put it in.

**Comment by alexdobin** [comment]
Hi Gery,
I would prefer to have the old solution for the SysV implementation - for backwards compatibility, and whichever solution you think is the best for the POSIX implementation.
Thanks a lot!
Alex

**Comment by gvessere** [comment]
sounds good! I'll try to put that in soon.

**Comment by gvessere** [comment]
So I added a new 1 byte shared memory segment that will take care of doing the process accounting. The same structure is used to manage the counter in both POSIX and SysV implementations.
Let me know how that looks...

**Comment by felixschlesinger** [comment]
Looks good to me.

**Comment by alexdobin** [comment]
Hi Gery,

finally pulled in your new version. All the test went through, it behaves as expected with all options. Thanks a lot for this contribution. I will make a new release with this and other changes hopefully on Monday.

Cheers
Alex

**Comment by kbullaughey** [comment]
Hi Alex,

I've noticed a few times you and others mention that all the tests pass. I am curious what sort of tests there are and whether these are available somewhere? I looked around in this repo for tests but couldn't find them. Great work on STAR, btw.

Cheers,
Kevin

**Comment by alexdobin** [comment]
Hi Kevin,

in these case we just tested the different shared memory options.
I do not have a formal test suite yet - typically I test each release on several ENCODE datasets making sure that the results do not change from release to release (or change in a predictable manner).

Cheers
Alex

**Comment by dinvlad** [comment]
Just to add to the conversation, using STAR in Docker containers this way requires running them with with `--ipc=host` option - otherwise they don't share the SysV namespace, and LoadAndRemove fails. Unfortunately, this option is not available in all container environments (e.g., I'm using it on AWS ECS), so one still has to resort to an alternative locking mechanism (either through /dev/shm or another shared filesystem).

**Pull request merged**
