### PR TITLE
GNU autotools based build (wip)

### LINKED ISSUE #49: recommend use of build system like autotools or cmake
for instance, users may already have a version of htslib installed which you could detect and link to automatically, as opposed to including it in your source.

it would also ease detection of compilers etc.

### PR DESCRIPTION
**Pull request by wookietreiber**
This adds a GNU Autotools based build to STAR, i.e. the following should successfully install STAR to `$HOME/STAR-autotools`:

```
git clone -b wip-autotools https://github.com/wookietreiber/STAR.git
cd STAR
autoreconf -fi
./configure --prefix=$HOME/STAR-autotools
make
make install
```

### Notes

-   fixes #49

-   I removed htslib from the distribution, it is checked via `pkg-config` to be available and
    provided by the system

-   the changes I made to the sources are negligible, mostly related to the external htslib and the
    rest should be mainly related to white space, I don't think I changed any *real* code

-   I also removed the included pre-built binaries, about that:

    -   personally, I don't like including binaries in a source code repository, it just clutters
        the repository

    -   the binaries can now be easily built, so there is no real need to include them

-   compiler flags are completely handled by Autotools which can be configured by setting `CXXFLAGS` in advance to running `./configure`, these flags include:

    -   whether or not to have a debug build or not (`-g`)

    -   optimization flags like `-O3`

    the default on Linux is `-g -O2`, I don't know what the default is for others platforms

-   use of OpenMP is now optional via the autoconf macro `AC_OPENMP`, enabled by default, disable via `configure --disable-openmp`

-   you can create the source distribution including the `configure` script with `make dist` for the GitHub releases page, this way, people who want to download a tagged release don't need neither Autotools installed nor run `autoreconf -fi`

### Still Missing from the Build

-   adding the build guidelines to the `README`

-   handling `COMPILE_FOR_MAC`, although this should most likely be done based on some autoconf variable that tracks for which platform to build, I would appreciate if someone with a MAC could get in touch with me about that

-   handling `COMPILE_FOR_LONG_READS`, I am thinking about either adding `STARlong` to
    `bin_PROGRAMS` or adding a `--enable-long-reads` flag to `configure`

### CODE REVIEW

**Comment by nathanhaigh** [comment]
Quick question as I don't much about the tools you've used.
  * Would this mean that htslib was then a dependency and needs to be installed before STAR? If so, the docs would need to have details of this.

**Comment by wookietreiber** [comment]
Yes, htslib would need to be installed before STAR. You need to simply follow the [htslib installation instructions](https://github.com/samtools/htslib/#building-htslib).

**Comment by wookietreiber** [comment]
@nathanhaigh the gist of autotools is that you divide your build into three separate steps (four if you build from a cloned repository):

0.  Create `configure` (source is `configure.ac`) and `Makefile.in` files (sources are `Makefile.am` files) This step is only needed if building from cloned repository and requires autoconf and automake. You do this by running:

        ./autogen.sh

1.  Configure your build by executing:

         ./configure [options]

    `./configure --help` lists all the options. This step checks that all defined dependencies for compilation of the actual source are available in a platform independent manner (at least across unixoid OSs, IIRC MS W requires something like Cygwin). Here you can set installation prefix and define paths of dependencies if they're installed in non-standard directories. This step creates the `Makefile` files out of the `Makefile.in` files with the configured information.

2.  Compile all sources by executing:

        make

3.  Install the software package by executing:

        [sudo] make install

    This installs to the configured installation prefix, which may require sudo rights, e.g. if you install to `/usr`.

The main advantage is the autotools does a lot for you and you do not need to manually edit a `Makefile` if you want to use different compilation flags, a different compiler, etc. Just export relevant environment variables like `CXXFLAGS` and re-run `./configure [options]`, the rest is done for you.

**Comment by alexdobin** [comment]
Hi Christian, Nathan,

this is a good example of a "complex pull request" in my view. It includes significant changes in project organization that I am not comfortable with. I am sorry for the delay, I finally have time to make a detailed response.

1. I prefer to keep the binaries inside the release, even though this is not a common approach. Many users are using pre-compiled binaries, and it's much easier for me to keep them inside the github repo rather than in a separate distribution.

2. To avoid backward/forward compatibility issues, I would rather include the htslib distribution, rather than rely on the outside installation of it. When samtools developers switched from original samtools API to the the htslib, I had to make non-trivial changes in the code. Aside from being non-elegant, I do not see any problems with this.

3. Not sure why we would want to compile without OMP support.

Cheers
Alex

**Comment by wookietreiber** [comment]
@alexdobin I respect your opinion on this matter. I am closing this PR for now.

**Pull request closed without merging**
